### ISSUE TITLE
[BUG] DQ - Match Code "Match column not propagated when empty"

### ISSUE THREAD

**Issue by gh4nh** [sassoftware/sas-studio-custom-steps#132] opened 2024-02-27 13:20 UTC
**Describe the bug**
In custom step "DQ - Match Code" when "match column" is left empty...
![image](https://github.com/sassoftware/sas-studio-custom-steps/assets/101747805/8d61eb17-7cf2-46b9-9252-e26a8d7e3b14)

... the table preview shows the column with *_MC ...
![image](https://github.com/sassoftware/sas-studio-custom-steps/assets/101747805/36c7b0ce-cc14-4736-877c-ac63b0dc0002)

... but in the column structure is not updated.
![image](https://github.com/sassoftware/sas-studio-custom-steps/assets/101747805/0767556c-51c9-46fb-851e-c9ff18d4f318)

**Comment by snlwih** [comment] 2024-03-13 12:55
@gh4nh, would you mind identifying yourself? Your GitHub profile does not have any information other then an old SAS Viya logo. Thanks.

**Comment by ArnoldToporowski** [comment] 2024-03-13 13:40
I don't see this problem (in release 2023.12)  Is there a release that this problem starts to appear?

**Comment by snlwih** [comment] 2024-03-13 14:44
@ArnoldToporowski , are you 100% sure?

**Comment by gh4nh** [comment] 2024-03-13 15:02
I found the issue with LTS 2023.10

SAS Institute GmbH, In der Neckarhelle 162, 69118 Heidelberg
Registergericht: Mannheim HRB-Nr. 332269, Gesch?ftsf?hrer: William David Davis

**Comment by ArnoldToporowski** [comment] 2024-03-13 15:57
> @ArnoldToporowski , are you 100% sure?

yes, I am not able to reproduce the problem.  Maybe Nicolaus can demo it?

**Comment by snlwih** [comment] 2024-03-13 16:58
Very simple to demo. Start with new flow, add input table, add DQMatch, select input column and match definition, Then click in output port and tab: column structure. See attached animated gif.
![DQMatch-ColumnStructure-missing-NewColumn](https://github.com/sassoftware/sas-studio-custom-steps/assets/35299890/852eec42-4bc4-4d04-b723-19222c25a7d0)

**Comment by ArnoldToporowski** [comment] 2024-03-13 17:10
OK, I see now.  I misunderstood the problem.  It does create the new matchcode column, but the new column name doesn't show up in the metadata.  When I'm using the step I don't see this problem because I always give the new column a name myself because I want to add the sensitivity level to the name (so NAME_MC85 instead of NAME_MC).

**Comment by lorenzotoja** [comment] 2024-03-15 06:45
Hi,
I remember well this peculiarity of custom step construction, but I don't agree with what you ask to do, i.e. removing all the controls from the Output Table Metadata panel in the Custom Step Designer, because the cure risks being worse than the disease!
Customers complain that column propagation is difficult and sometimes non-existent and forcing them to perform the step to see the columns would be annoying, tedious and not very productive (this is a widespread problem in SASStudio and a reason for fierce criticism of the software, especially for those who have used Data Integration).
The custom steps work like this, so it would be appropriate to specify it in the Readme or in general in the Git repository.
An alternative would be to specify a default name, but then you would have generic names and in the propagation you would see all the names even if only one selection was made.
We also remember that the DQ steps will be present as standard objects over time (DQ Match, for example, already exists and works without a column propagation ☹).
I reiterate my disappointment about this change, but if you insist I will make it (only for the git I will recommend the Italian version to my customers) when I have time.

L


Have a nice day 😊

Lorenzo Toja

**Comment by gh4nh** [comment] 2024-03-15 07:20
Salve Lorenzo,

Currently the step suggests in the definition that the field “Match Column” can be left empty and recommends “if empty will be used as input col_ with _MC suffix”.

A solution could be to mandatory enter a field-output-name or logic needs to be added to propagate the programmatically created output filed to the output column structure (if that is possible).

What is the „Italian version“ of that step?

Ciao,
Niko

SAS Institute GmbH, In der Neckarhelle 162, 69118 Heidelberg
Registergericht: Mannheim HRB-Nr. 332269, Geschäftsführer: William David Davis

**Comment by lorenzotoja** [comment] 2024-03-15 07:41
Ciao,
currently the Italian version is the one present in Git where there is the definition for propagating the columns. But if we eliminate it as Wilbram suggests the user is then forced to run the code to see the columns in subsequent steps. This behavior of SAS Studio is not very productive and annoying because it forces the developer not only to execute the code while developing it but also to create ad hoc tables to do this work, because it is unthinkable that the developer has to execute the code for each step especially if you are using huge tables even beyond tera bytes. If I eliminate column propagation I will only do so for the Git version. I believe that developers should use metadata (including new columns) as quickly as possible by running tests only at the end. Consequently, if the behavior of SAS Studio does not change, it is necessary to use work arounds and for these custom steps we have at least 3 possibilities:
1. Eliminate column propagation by forcing the developer to perform the step in order to see the columns
2. Explain in the Readme or in the notes that it is always good to write the name of the column even if the step would create it automatically (for these objects it is not possible to make the name mandatory, you could only put it for the first definition)
3. Put a default name on the column but this would show less significant names and they would all be seen in the subsequent steps even if not used

Finally you could ask for a feature that allows you to create names dependent on the names of the columns in this way the GUI itself would fill the name of the column deriving it from the name of the input column and adding the desired suffix or prefix (_MC for example)

Have a nice day 😊

Lorenzo Toja

**Comment by lorenzotoja** [comment] 2024-03-15 10:13
Hi,
perhaps I have a solution that would meet the two theories: by playing with the obligatory nature of the column name and the visibility dependencies we obtain the visibility of the output column without having to perform the custom step. The peculiarity remains in the fact that the developer must obligatorily enter the name of the output column and with this mechanism it is SAS Studio that verifies it by placing the not complete signal.

What do you think ?

***@***.***

Have a nice day 😊

Lorenzo Toja

**Comment by snlwih** [comment] 2024-03-15 15:24
@lorenzotoja , it is still not clear to me how a user would be able to use the newly created _MC column in subsequent steps when they have left the NewColumn control empty in the UI? Could you please explain?

**Comment by lorenzotoja** [comment] 2024-03-18 06:49
Hi,
with my new idea, the latest one I shot last week, the user cannot leave the field that defines the name of the variable empty (I would also modify the description) because it becomes mandatory. With the visibility of the column it is also possible to make the field become mandatory only if the user defines a second, third or other Matchcode. Having to specify the name SAS Studio requests the column and puts it in the output columns. Obviously this is a different way of working or, if you prefer, a workaround; the only side effect is that the user will have to specify the column name. It's an idea, not perfect perhaps, but it would avoid the execution of the step to see the columns in the next step. If you want, I'll send you the json of the step so you can check it

***@***.***


Have a nice day 😊

Lorenzo Toja

**Comment by snlwih** [comment] 2024-03-19 12:44
@lorenzotoja , that's exactly what we discussed many moons ago as the preferred solution. If you want to take advantage of column propagation at step usage time, the user will have to provide a value for the NewColumn control.And you as the step author can enforce that by marking the control as "required". 

On top of that, a NewColumn control that is marked as required but hidden, is ignored in terms of "being required" and therfore will not put the node in "incomplete" mode. However, there is caveat: hidden contols do not affect column propagation.  In other words, if you have a hidden NewColumn control and it has a value, that value will show up in the column structure of the output port even though the associated control is hidden. Although this might be sort of an edge case, you might want to create awareness for this. If it is too cumbersome to explain it in the UI itself, then mention it in the About tab and the readme.md. Have attached a small animated gif that shows this behaviour, hope that's useful. just wanted you to be aware of this.

![Custom Step - visibility rules and hidden objects](https://github.com/sassoftware/sas-studio-custom-steps/assets/35299890/cd6db2d1-0246-4161-ba3f-3cc6f1ec541d)


If you want to autogenerate new output column names using a naming convention, then you cannot use column propagation at usage time we've discussed at length in this thread. You would have to remove everything from the Output Table Metadata properties and fall back to having to run the step before columns are being available on the output port (and in subsequent steps). I

**Comment by lorenzotoja** [comment] 2024-03-19 13:11
this behavior is what I explained in my solution, having other things to do I had not investigated the fact that a hidden control does not affect the completeness of the node. I will edit DQ Match and DQ Standardize which I should have done. The DQ Identify has the same problem but I don't think I'm the author, at least I don't remember it

**Comment by snlwih** [comment] 2024-03-19 13:47
@lorenzotoja , sounds good. 

Have a tip for you around updating multiple steps. I would create dedicated branches in your forked repo, one branch for each of the DQ steps that you plan to update. Advantage being that you can create a dedicated pull request for each branch. 

If you would edit all of the steps in the same branch, a pull request would result in all those steps being added in the same pull request. This increases review time as there is more to review. Also when using a single pull request, a single issue with one specific step, will block publishing all of the other steps in the pull request 

Furthermore, if it takes some time to review the pull request and during that time you change something else in your forked repo and contribute it, that update/change will be added to the already open pull request on that branch.

**Comment by snlwih** [comment] 2024-03-19 13:58
Issue resolved by pull request #139. Going to close this entry.

**Closed by snlwih** 2024-03-19 13:58 UTC
